language: node_js
node_js:
 - "iojs"
before_script:
 - npm install -g grunt
script: grunt build

// before_script:
  // - "export DISPLAY=:99.0"
  // - "sh -e /etc/init.d/xvfb start" 
  // - 'node_modules/protractor/bin/webdriver-manager update --standalone --firefox'
  // - 'node_modules/protractor/bin/webdriver-manager start 2>&1 &'  
  // - sleep 3
  // - 'bower install'
  // - 'npm install grunt'
  // - 'npm install grunt-cli'
  // - 'npm install grunt-protractor-webdriver'
  // - 'npm install grunt-protractor-runner'
  // - 'npm install grunt-express-server'